---
- src: https://github.com/bossjones/boss-ansible-role-debug
- src: https://github.com/bossjones/ansible-role-tmux
- src: https://github.com/bossjones/ansible-role-tmuxinator
- src: https://github.com/bossjones/ansible-role-oh-my-zsh
- src: https://github.com/bossjones/boss-ansible-role-sysctl
- src: https://github.com/bossjones/ansible-role-osquery
- src: https://github.com/bossjones/boss-ansible-role-update-hosts
# https://github.com/suzuki-shunsuke/ansible-gvm

- src: https://github.com/zzet/ansible-rbenv-role
  name: zzet.rbenv
  version: 3.3.6

- src: https://github.com/Oefenweb/ansible-fail2ban
